name: advance_score
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - pytorch
  - torchvision
  - pytorch-cuda=12.1
  - numpy
  - pyyaml
  - tqdm
  - matplotlib
  - scipy
  - tensorboard
  - pip:
      - pytest
      - rich
