name: advance_score
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pytorch::pytorch
  - pytorch::torchvision
  - pytorch::pytorch-cuda=12.4
  - conda-forge::numpy
  - conda-forge::pyyaml
  - conda-forge::tqdm
  - conda-forge::matplotlib
  - conda-forge::scipy
  - conda-forge::tensorboard
  - pip:
      - pytest
      - rich
