base_config: ../base_toy.yaml

experiment:
  name: integrability_5way
  model_id: M0

loss:
  sigma0: 0.25
  lambda0: 0.20
  mu1: 0.20
  mu2: 0.20
  alpha: 0.20
  beta: 0.10
  sigma_c: 0.25
  reg_sym_method: jvp_vjp
  reg_sym_eps_fd: 1.0e-3
  delta_set: [0.02, 0.05, 0.10]
  cycle_knn_k: 8
  cycle_lengths: [3, 4, 5]
  cycle_samples: 64
  cycle_subset: null
  reg_freq: 1
  reg_low_noise_only: true

model:
  hybrid:
    high_type: mlp
    low_type: mlp_potential

eval:
  use_torch_fidelity: true
  enable_cycle_metrics: true
