base_config: ../base_mnist.yaml

experiment:
  name: integrability_5way
  model_id: M0

loss:
  sigma0: 0.50
  lambda0: 0.05
  mu1: 0.05
  mu2: 0.05
  alpha: 0.05
  beta: 0.025
  sigma_c: 0.50
  reg_sym_method: jvp_vjp
  reg_sym_eps_fd: 1.0e-3
  delta_set: [0.002, 0.004, 0.008]
  cycle_knn_k: 8
  cycle_lengths: [3, 4, 5]
  cycle_samples: 32
  cycle_subset: 64
  reg_freq: 1
  reg_low_noise_only: true

model:
  hybrid:
    high_type: unet
    low_type: potential_unet
    low_base_channels: 56

eval:
  use_torch_fidelity: true
  enable_cycle_metrics: true
